[package]
name = "swiss_json_knife"
version = "0.1.0"
authors = ["Sam Renick <samcrenick@gmail.com>"]
edition = "2018"

[dependencies]
actix-web="1.0"
serde = "1.0"
serde_json = "1.0"
actix-cors="0.1.0"
